# syntax=docker/dockerfile:1

# ===== Base/build stage =====
FROM node:20-bookworm-slim AS build
WORKDIR /app

ARG APP_NAME=dialogs-handler
ENV APP_NAME=${APP_NAME}

RUN apt-get update && apt-get install -y --no-install-recommends \
  python3 make g++ openssl ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY nest-cli.json ./
COPY tsconfig*.json ./

RUN npm ci --omit=dev && cp -r node_modules /tmp/prod_node_modules

RUN npm ci

COPY . .

ENV DATABASE_URL="postgresql://user:pass@localhost:5432/db"
RUN if [ "$APP_NAME" = "dialogs-handler" ]; then npx prisma generate; else echo "Skipping prisma generate for $APP_NAME"; fi


RUN npx nest build ${APP_NAME}

RUN npx nest build common

RUN mkdir -p dist/libs/common/src/config \
  && cp libs/common/src/config/prompts.json dist/libs/common/src/config/prompts.json

# ===== Runtime stage =====
FROM node:20-bookworm-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production


ARG APP_NAME=dialogs-handler
ENV APP_NAME=${APP_NAME}

RUN apt-get update && apt-get install -y --no-install-recommends \
  ca-certificates libssl3 \
  && rm -rf /var/lib/apt/lists/*

COPY --from=build /tmp/prod_node_modules ./node_modules
COPY --from=build /app/package*.json ./
COPY --from=build /app/dist/apps/${APP_NAME} ./dist/apps/${APP_NAME}
COPY --from=build /app/dist/libs ./dist/libs

EXPOSE 3100 3101 3102 3000

CMD ["sh", "-lc", "node dist/apps/$APP_NAME/main.js"]
